// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ASP.NETSample {
	
	
	public partial class Recovery {
		
		protected System.Web.UI.HtmlControls.HtmlForm login_form;
		
		protected System.Web.UI.WebControls.Button submit_recovery;
	}
}
